# Generated by Django 4.1.7 on 2023-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "company_status",
                    models.CharField(
                        choices=[
                            ("Layoffs", "Layoffs"),
                            ("Hiring", "Hiring"),
                            ("Hiring Freeze", "Hiring Freeze"),
                        ],
                        default="Hiring",
                        max_length=13,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now_add=True)),
                ("link", models.URLField(blank=True)),
                ("note", models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
