---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Installing pip
        run: pip install pipenv --upgrade
      - name: Stopping venv
        run: pipenv --rm
      - name: Installing dependencies
        run: pipenv install --system
      - name: Test
        run: pytest api/coronavstech -s -v --durations=0