name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: coronavstech.settings
      PYTHONPATH: /home/runner/testing/testing/api/coronavstech

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --system
          python -m pytest
