name: Pytest

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --system
          export PYTHONPATH=${{ vars.PYTHONPATH }}
          export DJANGO_SETTINGS_MODULE=${{ vars.DJANGO_SETTINGS_MODULE }}
          pytest -v -s
          pytest -v -s --rootdir= /home/runner/work/testing/testing/fibonacci

  fib_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --system
          export PYTHONPATH=${{ vars.PYTHONPATH }}
          export DJANGO_SETTINGS_MODULE=${{ vars.DJANGO_SETTINGS_MODULE }}
          pytest -v -s --rootdir= /home/runner/work/testing/testing/fibonacci
