---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --system
 # Install all dependencies, including development ones

      - name: Test
        run: pytest api/coronavstech -s -v --durations=0