name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --system
          pwd
          export PYTHONPATH=/home/runner/testing/testing/api/coronavstech
          export DJANGO_SETTINGS_MODULE=coronavstech.settings
          pytest -v -s
