---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Installing pip
        run: pip install pipenv --upgrade
      - name: Installing dependencies
        run: pipenv install --system
      - name: Test
        run: pytest api/coronavstech -s -v --durations=0
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"